# Generated by Django 4.1.5 on 2023-01-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='att_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
